#MULTIGRID:
#  SHORT_CYCLE: True
#  LONG_CYCLE: True
TRAIN:
  ENABLE: True
  DATASET: Smoke_gray
  BATCH_SIZE: 64
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  TOPK: 1
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [125, 160]
  TRAIN_CROP_SIZE: 112
  TEST_CROP_SIZE: 128
  INPUT_CHANNEL_NUM: [1, 1]  # GRAY
  MEAN: [0.45]
  STD: [0.225]
  HALF_FACE: False  # half face
  PATH_TO_TRAIN_DATA_TXT: "/data1/ADAS/gt_shuf_train.txt"
  PATH_TO_VAL_DATA_TXT: "/data1/ADAS/gt_shuf_val.txt"
  PATH_PREFIX: "/dataset/weiliqing/07_video_classification/01_dataset/"

SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  WIDTH_MULTI: 1.  # wdf
  GROUPS: 3  #  only support to shuffle net, [1, 3]
# **  Params  **
# SlowFastShuffleNet
#   Width=[1.0, 1.5, 2.0]
#   Groups=[1, 3]
# SlowFastShuffleNetV2
#    Width=[0.25, 0.5, 1.0, 1.5, 2.0]
# SlowFastMoibleNetV2
#   Width=[0.5, 0.7, 1.0, 2.0]
# SlowFastGhostNet
#   Width=[1.0, 1.5, 2.0]

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
#  STEPS: [0, 94, 154, 196]
  STEPS: [0, 20, 40, 50]
  MAX_EPOCH: 60 # 239
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-3
  WARMUP_EPOCHS: 3.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 2
  ARCH: slowfast
  MODEL_NAME: SlowFastShuffleNet  # SlowFastDualAttention
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5  # note, small model
TEST:
  ENABLE: True
  DATASET: Smoke_gray
  BATCH_SIZE: 128
  # wdf-add
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 1

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

# wdf-add
TENSORBOARD:
  ENABLE: True
  MODEL_VIS:
    ENABLE: False
  HISTOGRAM:
    ENABLE: False
  CONFUSION_MATRIX:
    ENABLE: False
    FIGSIZE: [80, 80]


NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /data1/ADAS/SMOKE_SlowFastShuffleNet_W1_G3
