# 224 * 224
# slowfast dual attention
# mobilenet
# train script:
# python /data1/SlowFast_tensorboard/SlowFast/tools/run_net.py --cfg /data1/SlowFast_tensorboard/SlowFast/configs/TIRED/DUAL_ATTENTION_TIRED_SLOWFAST_8x8_R50_MobileNetV2.yaml  NUM_GPUS 1 TRAIN.BATCH_SIZE 4  TEST.BATCH_SIZE 4

TRAIN:
  ENABLE: True
  DATASET: Wheel
  BATCH_SIZE: 8
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  TOPK: 1
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
#  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_TO_TRAIN_DATA_TXT: "/data1/ADAS/tired_detection/data/train/tired_detection_train_data.txt"  # 186317 folders
  PATH_TO_VAL_DATA_TXT: "/data1/ADAS/tired_detection/data/test/test_data_ori.txt"

SLOWFAST:
  ALPHA: 8
  BETA_INV: 4
  WIDTH_MULTI: 2.
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 3
  ARCH: slowfast
  MODEL_NAME: SlowFastMoibleNetV2  # model name
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: Wheel
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: False
# wdf-add
TENSORBOARD:
  ENABLE: True

NUM_GPUS: 0
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /data1/ADAS_TIRED_DUAL_MOBILE_NET_V2
