TRAIN:
  ENABLE: True
  DATASET: Wheel_GRAY
  BATCH_SIZE: 128
  EVAL_PERIOD: 1  # fix
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  TOPK: 1
  CHECKPOINT_FILE_PATH:  "" # "/data1/ADAS_TIRED_SLOW_R18/checkpoints/checkpoint_epoch_00034.pyth"

DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 2
  TRAIN_CROP_SIZE: 112
  TEST_CROP_SIZE: 128
  INPUT_CHANNEL_NUM: [1]
  MEAN: [0.45]
  STD: [0.225]
  HALF_FACE: True  # half face
  PATH_TO_TRAIN_DATA_TXT: "/data1/ADAS/tired_detection/data2/non_duplicate_train_data_0522_half_img.txt"
  PATH_TO_VAL_DATA_TXT: "/data1/ADAS/tired_detection/data2/non_duplicate_test_data_0528_half_img_no_sample_class.txt"

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 18
  SPATIAL_STRIDES: [[1], [1], [2], [2]]
  TRANS_FUNC: bottleneck_transform # basic_transform # bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[2], [2], [2], [2]]

NONLOCAL:
#  LOCATION: [[[]], [[1, 3]], [[1, 3, 5]], [[]]]  # wdf-fix, do not use non-local
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
#  MOMENTUM: 0.1
#  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.01
  LR_POLICY: cosine
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 3.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd  # wdf-fix sgd
MODEL:
  NUM_CLASSES: 3
  ARCH: slow
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: Wheel_GRAY
  BATCH_SIZE: 128
  # wdf-add
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
# wdf-add
TENSORBOARD:
  ENABLE: True
  MODEL_VIS:
    ENABLE: False
  HISTOGRAM:
    ENABLE: False
  CONFUSION_MATRIX:
    ENABLE: False


LOG_MODEL_INFO: True  # log model
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /data1/ADAS_TIRED_SLOW_R18_16_SCRATCH
