MULTIGRID:
  SHORT_CYCLE: False
  LONG_CYCLE: False
TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 512
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  PATH_PREFIX: "/dataset/guojietian/kinetics400/"
  NUM_FRAMES: 16
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [125, 160]
  TRAIN_CROP_SIZE: 112
  TEST_CROP_SIZE: 112
  INPUT_CHANNEL_NUM: [3, 3]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  WIDTH_MULTI: 2.0  # wdf
  GROUPS: 1  #  only support to shuffle net, [1, 3]
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
# **  Params  **
# SlowFastShuffleNet
#   Width=[1.0, 1.5, 2.0]
#   Groups=[1, 3]
# SlowFastShuffleNetV2
#    Width=[0.25, 0.5, 1.0, 1.5, 2.0]
# SlowFastMoibleNetV2
#   Width=[0.5, 0.7, 1.0, 2.0]
# SlowFastGhostNet
#   Width=[1.0, 1.5, 2.0]

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
#  STEPS: [0, 94, 154, 196]
  STEPS: [0, 30, 50, 70, 90, 95]
  MAX_EPOCH:  100 #239 239 #
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 14.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 400
  ARCH: slowfast
  MODEL_NAME: SlowFastShuffleNetV2  # SlowFastDualAttention
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

# wdf-add
TENSORBOARD:
  ENABLE: True
  MODEL_VIS:
    ENABLE: False
  HISTOGRAM:
    ENABLE: False
  CONFUSION_MATRIX:
    ENABLE: False
    FIGSIZE: [80, 80]

NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /data1/ADAS/KINETICS_SlowFastShuffleNetV2_W2_8GPU
